version: '3'
services:
    redis:
        image: redis:latest
        container_name: redis-db
        ports:
            - 6379:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]

    mysql:
        image: mysql
        container_name: mysql-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: nosql
            MYSQL_DATABASE: test_db
        ports:
            - "3306:3306"