version: '3'
services:
    redis:
        image: redis:latest
        container_name: redis
        restart: always
        network_mode: "host"
        ports:
            - 6379:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]

    mysql:
        image: mysql
        container_name: mysql
        restart: always
        network_mode: "host"
        volumes:
            - /home/andres/nosql/docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: nosql
            MYSQL_DATABASE: test_db
        ports:
            - 3306:3306

    cassandra1:
        image: cassandra:latest
        container_name: cassandra1
        restart: always
        network_mode: "host"
        ports:
            - 9042:9042
        volumes:
            - /home/andres/nosql/docker/cassandra/node1:/var/lib/cassandra/data
        environment:
            #- CASSANDRA_START_RPC=true
            - CASSANDRA_CLUSTER_NAME=MyCluster
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=datacenter1

    cassandra2:
        image: cassandra:latest
        container_name: cassandra2
        restart: always
        #network_mode: "host"
        ports:
            - 9043:9042
        volumes:
            - /home/andres/nosql/docker/cassandra/node2:/var/lib/cassandra/data
        # command: bash -c 'sleep 60;  /docker-entrypoint.sh cassandra -f'
        depends_on:
            - cassandra1
        environment:
            #- CASSANDRA_START_RPC=true
            - CASSANDRA_CLUSTER_NAME=MyCluster
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=datacenter1
            - CASSANDRA_SEEDS=192.168.1.99

    mongodb:
        image: mongo:latest
        container_name: mongodb
        network_mode: "host"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: nosql
            MONGO_INITDB_ROOT_PASSWORD: test_db
        ports:
          - 27017:27017
        volumes:
          - /home/andres/nosql/docker/mongodb:/data/db